# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/dual_arm_zynq/dual_arm_zynq.srcs/sources_1/bd/zb_simple/ip/zb_simple_processing_system7_0_0/zb_simple_processing_system7_0_0.xci
# IP: The module: 'zb_simple_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/dual_arm_zynq/dual_arm_zynq.srcs/sources_1/bd/zb_simple/ip/zb_simple_processing_system7_0_0/zb_simple_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_simple_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/parallels/dual_arm_zynq/dual_arm_zynq.srcs/sources_1/bd/zb_simple/ip/zb_simple_processing_system7_0_0/zb_simple_processing_system7_0_0.xci
# IP: The module: 'zb_simple_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/dual_arm_zynq/dual_arm_zynq.srcs/sources_1/bd/zb_simple/ip/zb_simple_processing_system7_0_0/zb_simple_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zb_simple_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
