# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zb_simple/zb_simple.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zb_simple || ORIG_REF_NAME==zb_simple} -quiet] -quiet

# IP: bd/zb_simple/ip/zb_simple_processing_system7_0_0/zb_simple_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zb_simple_processing_system7_0_0 || ORIG_REF_NAME==zb_simple_processing_system7_0_0} -quiet] -quiet

# XDC: bd/zb_simple/zb_simple_ooc.xdc
